model:
  embed_dim: 128
  num_head: 8
  num_labels: 3
  update_bert: False
  depth: 8

data:
  train_csv_path: '/scratch/dkayande/process/data/process2025/train_dataset_process.csv'
  val_csv_path: '/scratch/dkayande/process/data/process2025/val_dataset_process.csv'
  max_len: 250 

fbanks:
  num_mel_bins: 128
  sample_frequency: 16000
  use_energy: False
  frame_shift: 10
  frame_length: 25

wav2vec2_model_name_train: '/scratch/dkayande/process/data/process2025/process_w2v2_train_embeddings.pkl'
wav2vec2_model_name_val: '/scratch/dkayande/process/data/process2025/process_w2v2_val_embeddings.pkl'
bert_model_name: '/content/drive/MyDrive/process2025/bert_model'
phoneme_model_train: '/scratch/dkayande/process/data/process2025/process_bert_phoneme_train_embeddings.pkl'
phoneme_model_val: '/scratch/dkayande/process/data/process2025/process_bert_phoneme_val_embeddings.pkl'
egmpas_feats_train : '/scratch/dkayande/process/data/process2025/process_egmaps_train_features.pkl'
egmpas_feats_val : '/scratch/dkayande/process/data/process2025/process_egmaps_val_features.pkl'
trill_feats_train : '/scratch/dkayande/process/data/process2025/process_trill_train_embeddings.pkl'
trill_feats_val : '/scratch/dkayande/process/data/process2025/process_trill_val_embeddings.pkl'
bert_dir_val: '/scratch/dkayande/process/data/process2025/process_bert_val_embeddings.pkl'
bert_dir_train: '/scratch/dkayande/process/data/process2025/process_bert_train_embeddings.pkl'

training:
  batch_size: 4
  learning_rate: 4e-3
  warmup_steps: 200
  epochs: 10
  weight_decay : 1e-4
  checkpoint_path: '/scratch/dkayande/process/process2025/model_checkpoint_process.pth'
